### ISSUE TITLE
Error exporting Libs on Azure

### ISSUE THREAD

**Issue by dmoore247** [mrchristine/db-migration#6]
Using `python3 /databricks/driver/src/databricks-migration/export_db.py --profile DEFAULT --azure --libs`
Gives error message:
```Starting complete library log at 2020-02-27 18:58:06.480818
Get: https://eastus2.azuredatabricks.net/api/1.2/libraries/list
Traceback (most recent call last):
  File "/databricks/driver/src/databricks-migration/export_db.py", line 128, in <module>
    main()
  File "/databricks/driver/src/databricks-migration/export_db.py", line 67, in main
    lib_c.log_library_details()
  File "/databricks/driver/src/databricks-migration/dbclient/LibraryClient.py", line 18, in log_library_details
    all_libs = self.get('/libraries/list', version='1.2')
  File "/databricks/driver/src/databricks-migration/dbclient/dbclient.py", line 60, in get
    raise Exception("Error. GET request failed with code {}\n{}".format(http_status_code, raw_results.text))
Exception: Error. GET request failed with code 400
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 </title>
</head>
<body>
<h2>HTTP ERROR: 400</h2>
<p>Problem accessing /api/1.2/libraries/list. Reason:
<pre>    The V1 APIs for clusters and libraries are disabled. Please use the V2 APIs.</pre></p>
<hr />
</body>
</html>```

**Comment by mrchristine** [comment]
Disabled library export for now on Azure since the V2 APIs don't support listing all libs. Will file an improvement issue to track / investigate lib export on Azure.
